# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anasayfa.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(911, 699)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-20, -20, 1021, 761))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Adsız.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(140, 40, 631, 71))
        self.label_3.setObjectName("label_3")
        self.elemanlar = QtWidgets.QPushButton(Form)
        self.elemanlar.setGeometry(QtCore.QRect(380, 460, 141, 141))
        self.elemanlar.setObjectName("elemanlar")
        self.calismaozetleri = QtWidgets.QPushButton(Form)
        self.calismaozetleri.setGeometry(QtCore.QRect(380, 170, 141, 141))
        self.calismaozetleri.setObjectName("calismaozetleri")
        self.giriscikis = QtWidgets.QPushButton(Form)
        self.giriscikis.setGeometry(QtCore.QRect(690, 170, 141, 141))
        self.giriscikis.setObjectName("giriscikis")
        self.elemaneklecikar = QtWidgets.QPushButton(Form)
        self.elemaneklecikar.setGeometry(QtCore.QRect(50, 460, 141, 141))
        self.elemaneklecikar.setObjectName("elemaneklecikar")
        self.sistemdencik = QtWidgets.QPushButton(Form)
        self.sistemdencik.setGeometry(QtCore.QRect(690, 460, 141, 141))
        self.sistemdencik.setObjectName("sistemdencik")
        self.profil = QtWidgets.QPushButton(Form)
        self.profil.setGeometry(QtCore.QRect(60, 170, 141, 141))
        self.profil.setObjectName("profil")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#ffffff;\">ANA SAYFA</span></p></body></html>"))
        self.elemanlar.setText(_translate("Form", "Elemanlar"))
        self.calismaozetleri.setText(_translate("Form", "Çalışma Özetleri"))
        self.giriscikis.setText(_translate("Form", "Eleman Giriş-Çıkış"))
        self.elemaneklecikar.setText(_translate("Form", "Eleman Ekle-Çıkar"))
        self.sistemdencik.setText(_translate("Form", "Sistemden Çık"))
        self.profil.setText(_translate("Form", "Profil"))
