# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calismaozetleri.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1029, 768)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-30, -40, 1131, 891))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Adsız.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.goruntu = QtWidgets.QGraphicsView(Form)
        self.goruntu.setGeometry(QtCore.QRect(20, 80, 331, 311))
        self.goruntu.setObjectName("goruntu")
        self.calisansec = QtWidgets.QPushButton(Form)
        self.calisansec.setGeometry(QtCore.QRect(270, 410, 75, 23))
        self.calisansec.setObjectName("calisansec")
        self.departman = QtWidgets.QLineEdit(Form)
        self.departman.setGeometry(QtCore.QRect(750, 230, 151, 31))
        self.departman.setObjectName("departman")
        self.izingunu = QtWidgets.QLineEdit(Form)
        self.izingunu.setGeometry(QtCore.QRect(750, 380, 151, 31))
        self.izingunu.setObjectName("izingunu")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(190, 0, 631, 71))
        self.label_3.setObjectName("label_3")
        self.degerlendirme = QtWidgets.QLineEdit(Form)
        self.degerlendirme.setGeometry(QtCore.QRect(750, 460, 151, 31))
        self.degerlendirme.setObjectName("degerlendirme")
        self.ad = QtWidgets.QLineEdit(Form)
        self.ad.setGeometry(QtCore.QRect(750, 90, 151, 31))
        self.ad.setObjectName("ad")
        self.soyad = QtWidgets.QLineEdit(Form)
        self.soyad.setGeometry(QtCore.QRect(750, 160, 151, 31))
        self.soyad.setObjectName("soyad")
        self.pozisyon = QtWidgets.QLineEdit(Form)
        self.pozisyon.setGeometry(QtCore.QRect(750, 300, 151, 31))
        self.pozisyon.setObjectName("pozisyon")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(670, 70, 71, 67))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(630, 140, 111, 71))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(480, 530, 251, 51))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(500, 300, 337, 31))
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(430, 370, 337, 51))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(390, 450, 341, 51))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(490, 220, 331, 51))
        self.label_11.setObjectName("label_11")
        self.geciktigisure = QtWidgets.QLineEdit(Form)
        self.geciktigisure.setGeometry(QtCore.QRect(750, 540, 151, 31))
        self.geciktigisure.setObjectName("geciktigisure")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.calisansec.setText(_translate("Form", "Çalışan Seç"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#ffffff;\">ÇALIŞMA ÖZETLERİ</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#ffffff;\">Ad :</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#ffffff;\">Soyad :</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#ffffff;\">Geciktiği Süre (Dk) :</span></p></body></html>"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#ffffff;\">Pozisyon :</span></p></body></html>"))
        self.label_9.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#ffffff;\">Kullandığı İzin Günü :</span></p></body></html>"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#ffffff;\">Performans Değerlendirme :</span></p></body></html>"))
        self.label_11.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#ffffff;\">Departman :</span></p></body></html>"))
