# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'elemanlar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1063, 785)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-20, -20, 1121, 861))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Adsız.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(220, 30, 631, 71))
        self.label_3.setObjectName("label_3")
        self.elemanlar = QtWidgets.QTableWidget(Form)
        self.elemanlar.setGeometry(QtCore.QRect(200, 120, 661, 531))
        self.elemanlar.setObjectName("elemanlar")
        self.elemanlar.setColumnCount(0)
        self.elemanlar.setRowCount(0)
        self.getir = QtWidgets.QPushButton(Form)
        self.getir.setGeometry(QtCore.QRect(800, 670, 75, 23))
        self.getir.setObjectName("getir")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(130, 690, 201, 31))
        self.label_2.setObjectName("label_2")
        self.elemansayisi = QtWidgets.QLineEdit(Form)
        self.elemansayisi.setGeometry(QtCore.QRect(360, 700, 131, 20))
        self.elemansayisi.setObjectName("elemansayisi")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#ffffff;\">ELEMANLAR</span></p></body></html>"))
        self.getir.setText(_translate("Form", "Getir"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">Eleman Sayısı :</span></p></body></html>"))
