# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'giriscikis.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(906, 725)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-30, -70, 991, 861))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Adsız.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(130, 20, 631, 71))
        self.label_3.setObjectName("label_3")
        self.goruntu = QtWidgets.QGraphicsView(Form)
        self.goruntu.setGeometry(QtCore.QRect(70, 130, 391, 381))
        self.goruntu.setObjectName("goruntu")
        self.tani = QtWidgets.QPushButton(Form)
        self.tani.setGeometry(QtCore.QRect(390, 540, 75, 23))
        self.tani.setObjectName("tani")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(580, 300, 81, 41))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(550, 380, 111, 41))
        self.label_4.setObjectName("label_4")
        self.giris = QtWidgets.QPushButton(Form)
        self.giris.setGeometry(QtCore.QRect(650, 450, 75, 23))
        self.giris.setObjectName("giris")
        self.cikis = QtWidgets.QPushButton(Form)
        self.cikis.setGeometry(QtCore.QRect(750, 450, 75, 23))
        self.cikis.setObjectName("cikis")
        self.ad = QtWidgets.QLineEdit(Form)
        self.ad.setGeometry(QtCore.QRect(680, 310, 113, 20))
        self.ad.setObjectName("ad")
        self.soyad = QtWidgets.QLineEdit(Form)
        self.soyad.setGeometry(QtCore.QRect(680, 390, 113, 20))
        self.soyad.setObjectName("soyad")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#ffffff;\">GİRİŞ-ÇIKIŞ</span></p></body></html>"))
        self.tani.setText(_translate("Form", "Tanı"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600;\">Ad :</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600;\">Soyad :</span></p></body></html>"))
        self.giris.setText(_translate("Form", "Giriş"))
        self.cikis.setText(_translate("Form", "Çıkış"))
