# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'profil.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(922, 745)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-20, -40, 971, 821))
        self.label.setObjectName("label")
        self.mevcutsifre = QtWidgets.QLabel(Form)
        self.mevcutsifre.setGeometry(QtCore.QRect(-40, -30, 971, 821))
        self.mevcutsifre.setText("")
        self.mevcutsifre.setPixmap(QtGui.QPixmap("Adsız.png"))
        self.mevcutsifre.setScaledContents(True)
        self.mevcutsifre.setObjectName("mevcutsifre")
        self.goruntu = QtWidgets.QGraphicsView(Form)
        self.goruntu.setGeometry(QtCore.QRect(200, 100, 491, 371))
        self.goruntu.setObjectName("goruntu")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(100, 620, 131, 51))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(500, 590, 201, 31))
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(540, 550, 151, 31))
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(110, 590, 111, 41))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(150, 550, 81, 31))
        self.label_3.setObjectName("label_3")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(130, 20, 631, 71))
        self.label_9.setObjectName("label_9")
        self.ad = QtWidgets.QLineEdit(Form)
        self.ad.setGeometry(QtCore.QRect(260, 560, 113, 20))
        self.ad.setObjectName("ad")
        self.soyad = QtWidgets.QLineEdit(Form)
        self.soyad.setGeometry(QtCore.QRect(260, 600, 113, 20))
        self.soyad.setObjectName("soyad")
        self.unvan = QtWidgets.QLineEdit(Form)
        self.unvan.setGeometry(QtCore.QRect(260, 640, 113, 20))
        self.unvan.setObjectName("unvan")
        self.sifretekrar = QtWidgets.QLineEdit(Form)
        self.sifretekrar.setGeometry(QtCore.QRect(730, 600, 113, 20))
        self.sifretekrar.setObjectName("sifretekrar")
        self.yenisifre = QtWidgets.QLineEdit(Form)
        self.yenisifre.setGeometry(QtCore.QRect(730, 560, 113, 20))
        self.yenisifre.setObjectName("yenisifre")
        self.sifremidegistir = QtWidgets.QPushButton(Form)
        self.sifremidegistir.setGeometry(QtCore.QRect(770, 640, 101, 31))
        self.sifremidegistir.setObjectName("sifremidegistir")
        self.dogrula = QtWidgets.QPushButton(Form)
        self.dogrula.setGeometry(QtCore.QRect(720, 480, 101, 31))
        self.dogrula.setObjectName("dogrula")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">Unvan :</span></p></body></html>"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">Şifre Tekrar :</span></p></body></html>"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">Yeni Şifre :</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">Soyad :</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">Ad :</span></p></body></html>"))
        self.label_9.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#ffffff;\">PROFİL</span></p></body></html>"))
        self.sifremidegistir.setText(_translate("Form", "Şifremi Değiştir"))
        self.dogrula.setText(_translate("Form", "Doğrula"))
